# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/work/vivado/pynq/hdmi_io/hdmi_io.cache/wt [current_project]
set_property parent.project_path D:/work/vivado/pynq/hdmi_io/hdmi_io.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths C:/Xilinx/Vivado/_board_files [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_repo_paths d:/work/vivado/pynq/vivado-library [current_project]
set_property ip_output_repo d:/work/vivado/pynq/hdmi_io/hdmi_io.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/imports/hdl/bd_wrapper.v
add_files D:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/bd/bd/bd.bd
set_property used_in_implementation false [get_files -all d:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/bd/bd/ip/bd_rgb2dvi_0_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all d:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/bd/bd/ip/bd_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/bd/bd/ip/bd_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/bd/bd/ip/bd_dvi2rgb_0_0/src/ila_pixclk/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/bd/bd/ip/bd_dvi2rgb_0_0/src/ila_pixclk/ila_pixclk_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/bd/bd/ip/bd_dvi2rgb_0_0/src/ila_refclk/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/bd/bd/ip/bd_dvi2rgb_0_0/src/ila_refclk/ila_refclk_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/bd/bd/ip/bd_dvi2rgb_0_0/src/ila_timing_workaround.xdc]
set_property used_in_implementation false [get_files -all d:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/bd/bd/ip/bd_dvi2rgb_0_0/src/dvi2rgb.xdc]
set_property used_in_implementation false [get_files -all d:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/bd/bd/ip/bd_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/bd/bd/ip/bd_v_axi4s_vid_out_0_0/bd_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/bd/bd/ip/bd_v_axi4s_vid_out_0_0/bd_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/bd/bd/ip/bd_v_vid_in_axi4s_0_0/bd_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/bd/bd/ip/bd_v_vid_in_axi4s_0_0/bd_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/bd/bd/ip/bd_v_tc_0_0/bd_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/bd/bd/ip/bd_v_tc_0_0/bd_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/bd/bd/ip/bd_clk_wiz_0_0/bd_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/bd/bd/ip/bd_clk_wiz_0_0/bd_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/bd/bd/ip/bd_clk_wiz_0_0/bd_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/sources_1/bd/bd/bd_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/constrs_1/new/hdmi_io.xdc
set_property used_in_implementation false [get_files D:/work/vivado/pynq/hdmi_io/hdmi_io.srcs/constrs_1/new/hdmi_io.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top bd_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef bd_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file bd_wrapper_utilization_synth.rpt -pb bd_wrapper_utilization_synth.pb"
