# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/hdmi_io.xdc

# Block Designs: bd/bd/bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd || ORIG_REF_NAME==bd} -quiet] -quiet

# IP: bd/bd/ip/bd_rgb2dvi_0_0/bd_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_rgb2dvi_0_0 || ORIG_REF_NAME==bd_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_dvi2rgb_0_0/bd_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_dvi2rgb_0_0 || ORIG_REF_NAME==bd_dvi2rgb_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_v_axi4s_vid_out_0_0/bd_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==bd_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_v_vid_in_axi4s_0_0/bd_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==bd_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_v_tc_0_0/bd_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_v_tc_0_0 || ORIG_REF_NAME==bd_v_tc_0_0} -quiet] -quiet

# IP: bd/bd/ip/bd_clk_wiz_0_0/bd_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_clk_wiz_0_0 || ORIG_REF_NAME==bd_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/bd/bd_ooc.xdc
