webtalk_init -webtalk_dir d:/work/vivado/pynq/barrel_distortion_correction/vivado/hdmi_barrel_distortion_correction.sim/sim_1/behav/xsim/xsim.dir/tb_barrel_distortion_correction_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jun  9 17:28:00 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212440084_0_0_445" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cafb55e7-d54c-4c59-9dbf-3b83a3dfa238" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "307315d4b3a64804a0c802b235bdb127" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "220" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 8845H w/ Radeon 780M Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3793 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "29.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "512155 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.22_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "19772_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2670793134 -regid "212440084_0_0_445" -xml d:/work/vivado/pynq/barrel_distortion_correction/vivado/hdmi_barrel_distortion_correction.sim/sim_1/behav/xsim/xsim.dir/tb_barrel_distortion_correction_behav/webtalk/usage_statistics_ext_xsim.xml -html d:/work/vivado/pynq/barrel_distortion_correction/vivado/hdmi_barrel_distortion_correction.sim/sim_1/behav/xsim/xsim.dir/tb_barrel_distortion_correction_behav/webtalk/usage_statistics_ext_xsim.html -wdm d:/work/vivado/pynq/barrel_distortion_correction/vivado/hdmi_barrel_distortion_correction.sim/sim_1/behav/xsim/xsim.dir/tb_barrel_distortion_correction_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
